export const ErrorCodes = {
  // Auth
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',

  // Workspace
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',
  WORKSPACE_SLUG_CONFLICT: 'WORKSPACE_SLUG_CONFLICT',
  WORKSPACE_INVALID_ROLE: 'WORKSPACE_INVALID_ROLE',

  // Common & System
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Commerce & Domain (Batch 1 / Future placeholders)
  INVENTORY_NOT_ENOUGH: 'INVENTORY_NOT_ENOUGH',
  PURCHASE_INVALID_STATUS_TRANSITION: 'PURCHASE_INVALID_STATUS_TRANSITION',
  LISTING_COMPLIANCE_BLOCKED: 'LISTING_COMPLIANCE_BLOCKED',
  RAG_INSUFFICIENT_EVIDENCE: 'RAG_INSUFFICIENT_EVIDENCE',
  TOOL_TIMEOUT: 'TOOL_TIMEOUT',
  AI_STRUCTURED_OUTPUT_INVALID: 'AI_STRUCTURED_OUTPUT_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
