import { OperationAutomationService } from '../src/modules/operation-automation/operation-automation.service.js';

describe('A2: Automation Publish Truth Tests (OperationAutomationService)', () => {
  let service: OperationAutomationService;
  let mockPrisma: any;
  let mockToolCenter: any;
  let approvalRecord: any;

  beforeEach(() => {
    approvalRecord = {
      id: 'app_test_01',
      workspaceId: 'ws_demo',
      actionType: 'LISTING_PUBLISH',
      targetType: 'SKU',
      targetId: 'MTH-GREEN-001',
      requestedPayload: JSON.stringify({
        workflow: 'UPDATE_LISTING',
        skuCode: 'MTH-GREEN-001',
        price: 29.99,
        isDemoTemplate: true,
      }),
      status: 'PENDING',
      requestedAt: new Date(),
    };

    mockPrisma = {
      approval: {
        create: jest.fn().mockImplementation(async ({ data }) => {
          Object.assign(approvalRecord, data);
          return approvalRecord;
        }),
        findFirst: jest.fn().mockImplementation(async () => approvalRecord),
        update: jest.fn().mockImplementation(async ({ data }) => {
          Object.assign(approvalRecord, data);
          return approvalRecord;
        }),
      },
    };

    mockToolCenter = {
      executeTool: jest.fn().mockResolvedValue({
        success: true,
        data: { status: 'PASS' },
      }),
    };

    service = new OperationAutomationService(mockPrisma, mockToolCenter);
  });

  describe('Step 1 Copy Truthfulness', () => {
    it('Step 1 summary does not claim real-time AI generation', async () => {
      const run = await service.startListingPublishWorkflow(
        { skuCode: 'MTH-GREEN-001', targetPrice: 29.99 },
        'ws_demo',
      );

      const step1 = run.steps.find((s) => s.stepNumber === 1);
      expect(step1).toBeDefined();
      // Must not claim it was dynamically generated by AI for this run without template note
      expect(step1?.summary).not.toMatch(/已为 SKU .* 生成标题与 5 条已验证卖点/);
      expect(step1?.summary).toMatch(/模板|固定/);
    });
  });

  describe('Step 5 & 6 Publish Confirmation Truthfulness', () => {
    it('Mock execution does not set syncVerified=true or catalogStatus=ACTIVE', async () => {
      const initial = await service.startListingPublishWorkflow(
        { skuCode: 'MTH-GREEN-001', targetPrice: 29.99 },
        'ws_demo',
      );

      const completed = await service.approveAndExecute(initial.approvalId!, 'ws_demo');

      expect(completed.status).toBe('SUCCEEDED');
      expect(completed.result.isMock).toBe(true);
      expect(completed.result.mode).toBe('MOCK');
      expect(completed.result.syncVerified).toBe(false);
      expect(completed.result.catalogStatus).not.toBe('ACTIVE');
      expect(completed.result.catalogStatus).toBe('MOCK_SUBMITTED');
      expect(completed.result.publishedAt).toBeUndefined();

      const step6 = completed.steps.find((s) => s.stepNumber === 6);
      expect(step6).toBeDefined();
      expect(step6?.details.syncVerified).toBe(false);
      expect(step6?.details.catalogStatus).not.toBe('ACTIVE');
      expect(step6?.summary).not.toMatch(/已校验 ASIN 上线状态与 Seller Central 库存同步/);
    });

    it('RPA RUNNING or TIMEOUT does not result in SUCCEEDED or publish confirmation', async () => {
      // Mock actionRouter.dispatch to return RUNNING
      (service as any).actionRouter = {
        dispatch: jest.fn().mockResolvedValue({
          actionId: 'act_1',
          status: 'RUNNING',
          data: { jobId: 'job_running_01', status: 'RUNNING' },
          executionEvidence: {
            mode: 'LIVE',
            phase: 'SUBMITTED',
            effect: 'UNKNOWN',
            recovery: 'QUERY',
          },
        }),
      };

      const initial = await service.startListingPublishWorkflow(
        { skuCode: 'MTH-GREEN-001', targetPrice: 29.99 },
        'ws_demo',
      );

      const run = await service.approveAndExecute(initial.approvalId!, 'ws_demo');

      expect(run.status).not.toBe('SUCCEEDED');
      expect(run.result?.syncVerified).not.toBe(true);
      expect(run.result?.catalogStatus).not.toBe('ACTIVE');
      expect(run.result?.publishedAt).toBeUndefined();
    });

    it('Preserves RUNNING status and executionEvidence with UNKNOWN effect when upstream is RUNNING', async () => {
      const upstreamEvidence = {
        mode: 'MOCK' as const,
        provider: 'mock-rpa',
        operationId: 'pending-operation',
        phase: 'SUBMITTED' as const,
        effect: 'UNKNOWN' as const,
        recovery: 'MANUAL' as const,
        externalId: 'job_pending_01',
      };

      (service as any).actionRouter = {
        dispatch: jest.fn().mockResolvedValue({
          actionId: 'act_1',
          status: 'RUNNING',
          data: { jobId: 'job_pending_01', status: 'RUNNING' },
          executionEvidence: upstreamEvidence,
        }),
      };

      const initial = await service.startListingPublishWorkflow(
        { skuCode: 'MTH-GREEN-001', targetPrice: 29.99 },
        'ws_demo',
      );

      const run = await service.approveAndExecute(initial.approvalId!, 'ws_demo');

      expect(run.status).toBe('RUNNING');
      expect(run.result?.status).toBe('RUNNING');
      expect(run.result?.executionEvidence).toEqual(upstreamEvidence);
      expect(JSON.stringify(run)).toContain('UNKNOWN');

      const step5 = run.steps.find((s) => s.stepNumber === 5);
      expect(step5?.status).toBe('RUNNING');
      expect(step5?.details?.executionEvidence).toEqual(upstreamEvidence);
    });

    it('LIVE mode strictly forbids Demo template payload and throws DEMO_PAYLOAD_FORBIDDEN (WRITE_FORBIDDEN)', async () => {
      const initial = await service.startListingPublishWorkflow(
        { skuCode: 'MTH-GREEN-001', targetPrice: 29.99 },
        'ws_demo',
      );

      // Attempting LIVE execution on demo template must be strictly blocked
      await expect(
        service.approveAndExecute(initial.approvalId!, 'ws_demo', 'OP_ADMIN', {
          requestLiveExecution: true,
          userRole: 'OWNER',
        }),
      ).rejects.toThrow(/DEMO_PAYLOAD_FORBIDDEN.*WRITE_FORBIDDEN/);
    });

    it.each([
      ['undefined role', undefined],
      ['null role', null],
      ['empty string role', ''],
      ['OPERATOR role', 'OPERATOR'],
      ['VIEWER role', 'VIEWER'],
    ])(
      'LIVE mode fail-closed: %s strictly rejects LIVE execution before browser launch (dispatch count = 0)',
      async (_desc, rejectedRole) => {
        const dispatchSpy = jest.fn();
        (service as any).actionRouter = {
          dispatch: dispatchSpy,
        };

        approvalRecord = {
          id: 'app_real_fail_closed',
          workspaceId: 'ws_demo',
          actionType: 'LISTING_PUBLISH',
          targetType: 'SKU',
          targetId: 'REAL-SKU-888',
          requestedPayload: JSON.stringify({
            skuCode: 'REAL-SKU-888',
            price: 49.99,
            title: 'Authentic Real Marble Stand',
            isDemoTemplate: false,
            workflow: 'UPDATE_LISTING',
          }),
          status: 'PENDING',
          requestedAt: new Date(),
        };

        await expect(
          service.approveAndExecute('app_real_fail_closed', 'ws_demo', 'OP_TEST', {
            requestLiveExecution: true,
            userRole: rejectedRole as any,
          }),
        ).rejects.toThrow(/Playwright LIVE execution requires OWNER or ADMIN workspace role/);

        // Browser dispatch count strictly 0
        expect(dispatchSpy).not.toHaveBeenCalled();
      },
    );

    it('LIVE mode allows ADMIN role to proceed to dispatch', async () => {
      const dispatchSpy = jest.fn().mockResolvedValue({
        actionId: 'act_admin',
        status: 'SUCCEEDED',
        data: { jobId: 'job_admin_01' },
        executionEvidence: { mode: 'LIVE', phase: 'COMPLETED', effect: 'APPLIED' },
      });
      (service as any).actionRouter = { dispatch: dispatchSpy };

      approvalRecord = {
        id: 'app_real_admin',
        workspaceId: 'ws_demo',
        actionType: 'LISTING_PUBLISH',
        targetType: 'SKU',
        targetId: 'REAL-SKU-777',
        requestedPayload: JSON.stringify({
          skuCode: 'REAL-SKU-777',
          price: 39.99,
          title: 'Authentic Admin Granite Stand',
          isDemoTemplate: false,
          workflow: 'UPDATE_LISTING',
        }),
        status: 'PENDING',
        requestedAt: new Date(),
      };

      const result = await service.approveAndExecute('app_real_admin', 'ws_demo', 'OP_ADMIN', {
        requestLiveExecution: true,
        userRole: 'ADMIN',
      });

      expect(result.status).toBe('SUCCEEDED');
      expect(dispatchSpy).toHaveBeenCalledTimes(1);
    });

    it('Explicit HITL LIVE approval path on authentic non-demo payload reconstructs action, dispatches with executionMode=LIVE, sets syncVerified=true, and stores evidence', async () => {
      const liveEvidence = {
        mode: 'LIVE' as const,
        provider: 'playwright-rpa',
        operationId: 'live-operation',
        phase: 'COMPLETED' as const,
        effect: 'APPLIED' as const,
        recovery: 'AUTOMATIC' as const,
        evidence: {
          screenshotBefore: 'screenshot_before.png',
          screenshotAfter: 'screenshot_after.png',
          readBackVerified: true,
          traceZip: 'trace.zip',
        },
      };

      let capturedProposal: any;
      let capturedContext: any;
      (service as any).actionRouter = {
        dispatch: jest.fn().mockImplementation(async (proposal, context) => {
          capturedProposal = proposal;
          capturedContext = context;
          return {
            actionId: proposal.id,
            status: 'SUCCEEDED',
            data: {
              jobId: 'rpa_live_12345',
              status: 'SUCCESS',
              output: {
                sellerCentralUrl: 'https://sellercentral.amazon.com/inventory/view/REAL-SKU-999',
              },
            },
            executionEvidence: liveEvidence,
          };
        }),
      };

      // Non-demo approval record
      approvalRecord = {
        id: 'app_real_999',
        workspaceId: 'ws_demo',
        actionType: 'LISTING_PUBLISH',
        targetType: 'SKU',
        targetId: 'REAL-SKU-999',
        requestedPayload: JSON.stringify({
          skuCode: 'REAL-SKU-999',
          price: 59.99,
          title: 'Custom Stone Base Holder',
          workflow: 'UPDATE_LISTING',
          isDemoTemplate: false,
        }),
        status: 'PENDING',
        requestedAt: new Date(),
      };

      const completed = await service.approveAndExecute('app_real_999', 'ws_demo', 'OP_ADMIN', {
        requestLiveExecution: true,
        userRole: 'OWNER',
      });

      // Verify reconstructed Action parameters
      expect(capturedContext.executionMode).toBe('LIVE');
      expect(capturedContext.providerId).toBe('playwright-rpa');
      expect(capturedContext.isApproved).toBe(true);
      expect(capturedContext.approvedPayload.skuCode).toBe('REAL-SKU-999');
      expect(capturedContext.approvedPayload.price).toBe(59.99);
      expect(capturedContext.approvedPayload.workflow).toBe('UPDATE_LISTING');
      expect(capturedContext.approvedPayloadHash).toBeDefined();

      // Verify run outcomes for LIVE mode
      expect(completed.status).toBe('SUCCEEDED');
      expect(completed.result.isMock).toBe(false);
      expect(completed.result.mode).toBe('LIVE');
      expect(completed.result.syncVerified).toBe(true);
      expect(completed.result.catalogStatus).toBe('VERIFIED');
      expect(completed.result.sellerCentralUrl).toBe(
        'https://sellercentral.amazon.com/inventory/view/REAL-SKU-999',
      );

      const step5 = completed.steps.find((s) => s.stepNumber === 5);
      expect(step5?.name).toBe('RPA 提交 Seller Central (Playwright)');
      expect(step5?.status).toBe('COMPLETED');
      expect(step5?.summary).toMatch(/Read-back Verify: PASS/);

      const step6 = completed.steps.find((s) => s.stepNumber === 6);
      expect(step6?.name).toBe('发布后回传与页面核验（真实执行）');
      expect(step6?.details.syncVerified).toBe(true);
      expect(step6?.details.catalogStatus).toBe('VERIFIED');
      expect(step6?.details.mode).toBe('LIVE');
    });
  });
});
