'use client';

import React, { useState } from 'react';
import type { OperationsRecommendationView } from '@crosspilot/shared';
import { Button } from '@/components/ui/button';
import { StatusPill } from '@/components/ui/page-header';
import { getStatusLabel } from '@/constants/ui-labels';

function pillTone(status: string): 'warning' | 'success' | 'accent' | 'neutral' | 'danger' {
  if (status === 'WAITING_APPROVAL' || status === 'GENERATED') return 'warning';
  if (status === 'APPROVED' || status === 'EXECUTED' || status === 'VERIFIED') return 'success';
  if (status === 'REJECTED') return 'danger';
  return 'neutral';
}

export function RecommendationCenter({
  items,
  isViewer,
  busyId,
  onApprove,
  onDraftFromVoc,
  canDraft,
  draftBusy,
}: {
  items: OperationsRecommendationView[];
  isViewer: boolean;
  busyId: string | null;
  onApprove: (id: string) => Promise<void>;
  onDraftFromVoc?: () => Promise<void>;
  canDraft?: boolean;
  draftBusy?: boolean;
}) {
  const [openId, setOpenId] = useState<string | null>(
    items.find((item) => item.status === 'WAITING_APPROVAL')?.id ?? items[0]?.id ?? null,
  );

  if (!items.length) {
    return (
      <section className="cp-panel px-5 py-6">
        <h2 className="text-[15px] font-semibold tracking-tight">Recommended actions</h2>
        <p className="mt-1 max-w-[65ch] text-[13px] text-fg-muted">
          No playbook recommendations yet. Draft one from current VOC. Confirming never writes to Amazon.
        </p>
        {canDraft && onDraftFromVoc ? (
          <div className="mt-4">
            <Button variant="secondary" disabled={draftBusy} onClick={onDraftFromVoc}>
              {draftBusy ? 'Drafting…' : 'Draft from VOC'}
            </Button>
          </div>
        ) : null}
      </section>
    );
  }

  return (
    <section>
      <div className="mb-3 flex flex-wrap items-end justify-between gap-3">
        <div>
          <h2 className="text-[15px] font-semibold tracking-tight">Recommended actions</h2>
          <p className="mt-1 text-[13px] text-fg-muted">
            Confirm the decision. Execution stays ledger-only in this version.
          </p>
        </div>
        {canDraft && onDraftFromVoc ? (
          <Button variant="secondary" disabled={draftBusy} onClick={onDraftFromVoc}>
            {draftBusy ? 'Drafting…' : 'Draft from VOC'}
          </Button>
        ) : null}
      </div>
      <div className="space-y-2">
        {items.map((item) => {
          const open = openId === item.id;
          const canApprove = !isViewer && item.status === 'WAITING_APPROVAL';
          return (
            <article key={item.id} className="cp-panel">
              <button
                type="button"
                className="flex w-full items-start justify-between gap-3 px-5 py-4 text-left"
                onClick={() => setOpenId(open ? null : item.id)}
              >
                <div>
                  <div className="flex flex-wrap items-center gap-2">
                    <StatusPill tone={pillTone(item.status)}>{getStatusLabel(item.status)}</StatusPill>
                    <span className="text-[12px] text-fg-muted">{item.generatedBy}</span>
                  </div>
                  <h3 className="mt-2 text-[15px] font-semibold tracking-tight">{item.decision}</h3>
                  <p className="mt-1 max-w-[70ch] text-[13px] leading-relaxed text-fg-muted">{item.reason}</p>
                </div>
              </button>
              {open ? (
                <div className="space-y-3 border-t border-border px-5 py-4">
                  <Meta label="Reason" value={item.reason} />
                  <Meta
                    label="Evidence"
                    value={item.evidenceQuotes.length ? item.evidenceQuotes.join('\n') : 'No evidence quotes stored'}
                  />
                  <Meta label="Generated by" value={item.generatedBy} />
                  <Meta label="Created" value={new Date(item.createdAt).toLocaleString()} />
                  {canApprove ? (
                    <Button
                      disabled={busyId === item.id}
                      onClick={() => onApprove(item.id)}
                    >
                      {busyId === item.id ? 'Confirming…' : 'Confirm recommendation'}
                    </Button>
                  ) : isViewer && item.status === 'WAITING_APPROVAL' ? (
                    <p className="text-[12px] text-fg-muted">VIEWER can read this decision but cannot confirm it.</p>
                  ) : null}
                </div>
              ) : null}
            </article>
          );
        })}
      </div>
    </section>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[11px] uppercase tracking-[0.14em] text-fg-muted">{label}</div>
      <p className="mt-1 whitespace-pre-line text-[13px] leading-relaxed">{value}</p>
    </div>
  );
}
